### ISSUE TITLE
User can view the home page

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#1]
## 💰 Motivation

The user will see the home page

## 📐 Plan

Make the home page for the program with a small preview of the top anime and a couple of random anime.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/108790375-65ff2780-7531-11eb-86ec-149c3b02b7fc.png)

## ✅ Task List

- [x] Create the HTML skeleton.
- [x] Use CSS to make the HTML similar to the Wireframe.
- [x] Use CSS to make the HTML adapt to a bigger screen.
- [x] Get the top 3 top rated anime and display them.
- [x] Create a function that grabs random anime and display them on the home page.
- [x] Check for any unnecessary CSS, Html or JavaScript code. 
- [x] Final Check code for any errors.
