### ISSUE TITLE
User can see info

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#18]
## 💰 Motivation

The user will see be able to see more information on an anime when clicked on.

## 📐 Plan

Let the user click on any anime for more information.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/109729366-9d428980-7b6c-11eb-82a9-842f57770589.png)

![image](https://user-images.githubusercontent.com/54919527/109730195-f6f78380-7b6d-11eb-8704-a9c24faf543b.png)

## ✅ Task List

- [x] Make the anime container clickable.
- [x] Hide all other elements that are unnecessary.
- [x] Place anime information inside an object to display on page.
- [ ] Check for useless CSS,HTML and JavaScript code.
- [ ] Final check code.
