### ISSUE TITLE
User can see random anime

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#3]
## 💰 Motivation

The user will see random anime that can be added to their list
## 📐 Plan

Use a function to populate the containers with random anime

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/108790724-43b9d980-7532-11eb-9f28-7e737fe65060.png)

## ✅ Task List

- [x] Create a variable to check what page the user is on.
- [x] Use JSON to save current page
- [x] Delete manual inputted code
- [x]  Switch over to creating a tree and appending it to the list.
- [x] Check for any errors or useless code
- [x] Final Check code
