### ISSUE TITLE
User can see top rated

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#4]
## 💰 Motivation

The user will see be able to see the top anime and can add them to their favorites

## 📐 Plan

Use a function to populate the containers with the top rated anime

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/54919527/109199468-59a6e480-7754-11eb-9643-8a4b93f5eaec.png)

## ✅ Task List

- [x] Use querySelector to get top-rated button.
- [x] Make a condition statement to check if top-rated button was clicked.
- [x] Check code for useless CSS, Html and JavaScript.
- [x] Final check code
