### ISSUE TITLE
User can search for genre

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#5]
## 💰 Motivation

The user will see be able to see  a list of the genre that they searched for.
## 📐 Plan

Use a function to populate the containers with the searched result.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/108791067-11f54280-7533-11eb-8e99-932f8937b32b.png)

## ✅ Task List

- [x] Use querySelector to get input from the search bar.
- [x] Make a function that will request a genre to the API.
- [x] Check if the search button was clicked and change screen.
- [x] Make changes to the dom tree.
- [x] Check for any useless Code.
- [x] Final Check code.
