### ISSUE TITLE
User can search for anime

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#6]
## 💰 Motivation

The user will see be able to see the anime that they searched for.

## 📐 Plan

Use a function to search for a show and view the description of it.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/109240812-04d39000-778d-11eb-957f-75c9257e740b.png)

## ✅ Task List

- [x] Fix search input genre
- [x] Create a function that searches for anime title
- [x] Create an html skeleton for an individual item.
- [x] Change current page to hidden and display only the anime.
- [x] Check for useless code.
- [x] Final Check
