### ISSUE TITLE
User can see their favorite list

### ISSUE THREAD

**Issue by Andy-Duenas** [Andy-Duenas/ajax-project#8]
## 💰 Motivation

The user will see their favorite list of anime

## 📐 Plan

Create an object of the user that stores their favorite anime and display the list with an option to sort the list by rating.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/54919527/108790663-22f18400-7532-11eb-9a7b-fa61721c0837.png)

## ✅ Task List

- [x] Create an object of users list and save it to local storage.
- [x] Make awesome fonts icon clickable.
- [x] Create a function that push's the object into the favorites list.
- [x] Delete previous trees and only show list.
- [x] Check code for useless lines.
- [x] Final Check
